# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_hat_mat_list <- function(X) {
    .Call(`_GBoost_compute_hat_mat_list`, X)
}

model_fitting <- function(X, y, x_size, total_steps, step_size, adj_var, stop_tol = 1e-5, gamma = 0, stop_method = "AIC") {
    .Call(`_GBoost_model_fitting`, X, y, x_size, total_steps, step_size, adj_var, stop_tol, gamma, stop_method)
}

